spring:
  profiles:
    active: dev  #当前激活profile
---
server:
  port: 8080
spring:
  profiles: dev #开发环境
  messages:
    basename: i18n/messages,i18n/pages  #指定classpath下的资源文件路径
    encoding: UTF-8 #资源文件编码，默认
    cache-duration: 2 #缓存持续时间（s），默认永久缓存
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      location: "/"
      file-size-threshold: 512KB #超过指定大小，则写入磁盘
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dept8001
    username: root
    password: mysqladmin
    filters: stat,wall
    dbcp2:  #数据库连接池
      initial-size: 5
      max-idle: 5
      min-idle: 5
      max-total: 10
      max-wait-millis: 200
mybatis-plus:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.learn.model
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
---
server:
  port: 9090
spring:
  profiles: beta  #测试环境
  messages:
    basename: i18n/messages,i18n/pages  #指定classpath下的资源文件路径
    encoding: UTF-8 #资源文件编码，默认
    cache-duration: 2 #缓存持续时间（s），默认永久缓存
---
server:
  port: 80
spring:
  profiles: product #线上
  messages:
    basename: i18n/messages,i18n/pages  #指定classpath下的资源文件路径
    encoding: UTF-8 #资源文件编码，默认
    cache-duration: 2 #缓存持续时间（s），默认永久缓存
